# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class UploadImage201Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UploadImage201Response - a model defined in OpenAPI

        key: The key of this UploadImage201Response [Optional].
        url: The url of this UploadImage201Response [Optional].
    """

    key: Optional[str] = Field(alias="key", default=None)
    url: Optional[str] = Field(alias="url", default=None)


UploadImage201Response.update_forward_refs()
