# coding: utf-8

"""
    Scavenger Image Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""
import os

import uvicorn
from fastapi import FastAPI

from image_service.apis.core_api import router as CoreApiRouter
from image_service.apis.diagnostic_api import router as DiagnosticApiRouter

app = FastAPI(
    title="Scavenger Image Service",
    version="0.1",
)

app.include_router(CoreApiRouter)
app.include_router(DiagnosticApiRouter)

print(f'USING AWS PROFILE: {os.environ.get("AWS_PROFILE")}')


def run_server():
    """Launched with `poetry run start` at root level"""
    uvicorn.run(
        "image_service.main:app",
        host=os.environ.get("IMAGE_SERVICE_SERVER_HOST", "0.0.0.0"),
        port=int(os.environ.get("IMAGE_SERVICE_SERVER_PORT", 8000)),
        reload=True,
    )


if __name__ == "__main__":
    run_server()
